### ISSUE TITLE
python -m augmentation ERROR

### ISSUE THREAD

**Issue by gzxiong** [saturn-lab/audioNet#11]
{"created":"@1563761708.103627638","description":"No address added out of total 1 resolved","file":"src/core/ext/transport/chttp2/server/chttp2_server.cc","file_line":302,"referenced_errors":[{"created":"@1563761708.103621246","description":"Failed to add any wildcard listeners","file":"src/core/lib/iomgr/tcp_server_posix.cc","file_line":337,"referenced_errors":[{"created":"@1563761708.103568034","description":"OS Error","errno":97,"file":"src/core/lib/iomgr/socket_utils_common_posix.cc","file_line":256,"os_error":"Address family not supported by protocol","syscall":"socket","target_address":"[::]:50051"},{"created":"@1563761708.103616063","description":"Unable to configure socket","fd":6,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":200,"referenced_errors":[{"created":"@1563761708.103607417","description":"OS Error","errno":98,"file":"src/core/lib/iomgr/tcp_server_utils_posix_common.cc","file_line":173,"os_error":"Address already in use","syscall":"bind"}]}]}]}

**Comment by zhenchen3419** [comment]
"os_error":"Address already in use", 应该是启动了两个 augmentation任务。 @TeDdy-123

**Comment by gzxiong** [comment]
原因：没有停下项目的情况下，关闭IDE，或者是之前的项目没有停掉，又一次运行了本项目．

解决办法：前者很简单，杀死进程．后者更简单把正在run的项目停掉．
杀死进程的命令：

如果是查看本机所有的进行的进程：

ps aux　#　用 ps -A 查看所有进程
杀死进程： kill -9 PID # PID是进程号,查看进程时会显示
--------------------- 
作者：python吴彦祖 
来源：CSDN 
原文：https://blog.csdn.net/Tian_rc/article/details/86678370 
版权声明：本文为博主原创文章，转载请附上博文链接！

**Comment by zhenchen3419** [comment]
对的。
