### ISSUE TITLE
audioNet模型训练到2999/3000时停止了

### ISSUE THREAD

**Issue by BertramRay** [saturn-lab/audioNet#8]
2997/3000 [============================>.] - ETA: 2s - loss: 0.6882 - acc: 0.8388
2998/3000 [============================>.] - ETA: 1s - loss: 0.6880 - acc: 0.8388
2999/3000 [============================>.] - ETA: 0s - loss: 0.6878 - acc: 0.8389
此后便不再运行

**Comment by Lucius-lsr** [comment]
Epoch 1/1
2019-07-20 11:16:46.744679: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2999/3000 [============================>.] - ETA: 0s - loss: 0.5786 - acc: 0.8657

**Comment by HaoyunHong** [comment]
其实。。。就算我卸载了CPU版本的TF，安装了GPU版本的TF（因为我的电脑可以用）及其环境，但是。。。依然是在第一个epoch的最后一个点卡住了，我觉得应该是我们现在用的工具的版本新，和当年写的代码中类似于保存功能的部分不兼容，导致程序跑飞了。代码还没有完全看懂（没有注释真的呜呜），等看懂了再改一改有可能能解决。

**Comment by ritou11** [comment]
检查TensorFlow版本？如果反复运行依然如此，建议降级到1.10.0，此程序在该版本的TensorFlow得到过大量验证。

**Comment by ritou11** [comment]
探究这个问题的成因，可以试试调试并找到关键语句，然后大家讨论下问题成因ヾ(◍°∇°◍)ﾉﾞ

**Comment by LGXNOTLGX** [comment]
降低tensorflow的版本好像不得行，我降到了1.10.0的版本，还是卡到了最后一步

**Comment by HaoyunHong** [comment]
很可能是老师说的“grpc调用出错"（虽然这个我还不太懂），感觉上和tensorflow以及python的版本都有关系，因为我这里跑的时候，最前面会出很多warning，大多都说现在这个不用了、过时了，请换成另一种写法法，我有怀疑过可能和keras的版本也有关系，因为里面也有keras2是怎么样的，但是代码里是keras1的版本之类的warning。工具的版本不一致可能导致client和service的通信代码需要进行改变。

**Comment by LGXNOTLGX** [comment]
刚刚更新了一下这个代码，问题已经解决
我觉得造成这个问题的原因是model.fit_generator这个function调用数据错误
其中的validation_*=test不应该出现在这里，删除后问题得到解决（我认为这是根本原因）
还修改了其他两处才使得程序能够正常运行
1.修改了model.py中的Conv2D的参数内容，以及更新了对应的keras2的参数变量
2.修改了train.py中的model.fit_generator中的一些参数，更新了对应的keras2的内容
3.删除了在计算权重时的循环，将权重保存单独设为一个变量，默认每一个时代保存一个权重
